name: Java CI with Maven

on:
  push:
    branches: [ "integration" ]
  pull_request:
    branches: [ "integration" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven

      - name: Setup Maven
        uses: actions/setup-maven@v2
        with:
          maven-version: '3.9.5'

      - name: Build with Maven
        run: mvn -B clean verify --file pom.xml
        working-directory: ./address-book
