name: Java CI with Maven

on:
  push:
    branches: [ "integration" ]
  pull_request:
    branches: [ "integration" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'maven'

      - name: Manually setup Maven
        run: |
          curl -sL https://downloads.apache.org/maven/maven-3/3.9.5/binaries/apache-maven-3.9.5-bin.tar.gz | tar xz -C $HOME
          echo "MAVEN_HOME=$HOME/apache-maven-3.9.5" >> $GITHUB_ENV
          echo "$HOME/apache-maven-3.9.5/bin" >> $GITHUB_PATH

      - name: Setup xvfb
        run: |
          sudo apt-get install -y xvfb
          Xvfb :99 & 
          echo "DISPLAY=:99.0" >> $GITHUB_ENV

#      - name: Generate Javadoc
#        run: |
#          for dir in $(find . -mindepth 2 -name 'pom.xml' -printf '%h\n'); do
#            (cd $dir && mvn javadoc:javadoc)
#          done
#      - name: List Javadoc directory
#        run: ls -l target/site/javadoc


      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: docs/javadoc
          token: ${{ secrets.YOUR_SECRET_NAME }}

      - name: Build and test with Maven
        run: mvn -B clean verify --file pom.xml
